spring:
    application:
      name: gateway-server
    cloud:
      gateway:
          routes:
              - id: eureka-client-1
                uri: http://localhost:8081
                predicates:
                    - Path=/eureka-client-1/**
              - id: eureka-client-2
                uri: http://localhost:8082
                predicates:
                    - Path=/eureka-client-2/**

server:
    port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka